// backend/routes/authRoutes.js
const express = require('express');
const { body } = require('express-validator');
const rateLimit = require('express-rate-limit');
const { verifyToken } = require('../middleware/authMiddleware');
const validateRequest = require('../middleware/validateMiddleware');
const { refreshLimiter } = require('../middleware/rateLimitMiddleware');

const {
  register,
  login,
  refresh,
  logout,
  getMe,
  forgotPassword,
  resetPassword,
  verifyEmail,
  updateMe,
  addAddress,
  deleteAddress,
  addGarageBike,
  setPrimaryBike,
  deleteGarageBike,
  googleAuth
} = require('../controllers/authController');

const router = express.Router();

// Strict Rate Limiting Surcharges for Authentication Vectors
const registrationLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 Hour window
  max: 10,
  message: { success: false, message: 'Registration threshold exceeded. Try again later.' }
});

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 Minute freeze window
  max: 5,
  message: { success: false, message: 'Too many login attempts. Access frozen for 15 minutes.' }
});

const forgotPasswordLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 Hour window
  max: 3,
  message: { success: false, message: 'Too many reset requests. Try again in an hour.' }
});

// ============================================================================
// 🔐 PUBLIC / GUEST AUTHENTICATION ROUTES
// ============================================================================

router.post(
  '/register',
  registrationLimiter,
  [
    body('name').notEmpty().withMessage('Name is required.').trim(),
    body('email').isEmail().withMessage('Valid email required.').normalizeEmail(),
    body('phone').isLength({ min: 10, max: 15 }).withMessage('Phone must be 10-15 digits.').trim(),
    body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters.'),
    validateRequest
  ],
  register
);

router.post(
  '/login',
  loginLimiter,
  [
    body('email').isEmail().withMessage('Valid email required.').normalizeEmail(),
    body('password').notEmpty().withMessage('Password is required.'),
    validateRequest
  ],
  login
);

router.post('/refresh', refreshLimiter, refresh);
router.post('/forgot-password', forgotPasswordLimiter, forgotPassword);
router.post('/reset-password', resetPassword);
router.get('/verify-email/:token', verifyEmail);

// 🔥 CORE GOOGLE ENDPOINT: Captures and handles SDK access tokens generated by Login.jsx popups
router.post('/google', googleAuth);

// ============================================================================
// 🛡️ PROTECTED RIDER SESSION ACCOUNT CONFIGURATION ROUTES
// ============================================================================

router.post('/logout', verifyToken, logout);
router.get('/me', verifyToken, getMe);
router.put('/me', verifyToken, updateMe);

// Address sub-ledger management handlers
router.post('/addresses', verifyToken, addAddress);
router.delete('/addresses/:id', verifyToken, deleteAddress);

// "My Garage" component registration hooks
router.post('/garage', verifyToken, addGarageBike);
router.put('/garage/:id/primary', verifyToken, setPrimaryBike);
router.delete('/garage/:id', verifyToken, deleteGarageBike);

module.exports = router;